using MassTransit;
using MassTransit.Transports;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Models.Data;
using Models.Entities;
using Models.Entities.DTO;
using Models.Entities.Enums;
using Web.Models;
using Web.Services;

namespace Web.Controllers;

public class OrdersController : Controller {
	private readonly LocalDbContext _localContext;
	private readonly GlobalDbContext _globalContext;
	private readonly Utilities _utilities;
	private readonly ISendEndpointProvider _sendEndpointProvider;
	private readonly IConfiguration _configuration;
	private readonly UserManager<CoffeeUser> _userManager;

	public OrdersController(
		LocalDbContext localContext,
		GlobalDbContext globalContext,
		Utilities utilities,
		ISendEndpointProvider sendEndpointProvider,
		IConfiguration configuration,
		UserManager<CoffeeUser> userManager) {
		_localContext = localContext;
		_globalContext = globalContext;
		_utilities = utilities;
		_sendEndpointProvider = sendEndpointProvider;
		_configuration = configuration;
		_userManager = userManager;
	}

	// GET: Orders
	public async Task<IActionResult> Index() {
		var orders = await _localContext.Orders.Include(o => o.CoffeeUser).ToListAsync();
		return View(orders);
	}

	// GET: Orders/Details/5
	public async Task<IActionResult> Details(long? id) {
		if (id == null)
			return NotFound();

		var order = await _localContext.Orders
			  .Include(o => o.CoffeeUser)
			  .FirstOrDefaultAsync(m => m.Id == id);

		if (order == null)
			return NotFound();

		return View(order);
	}

	// GET: Orders/Create
	public async Task<IActionResult> Create() {
		ViewData["CoffeeUserId"] = new SelectList(_localContext.Users, "Id", "FirstName");
		ViewData["CoffeeTypes"] = _utilities.GetEnumSelectList<CoffeeType>(ignored: ["Unknown"]);
		ViewData["StatusTypes"] = _utilities.GetEnumSelectList<StatusType>(ignored: ["Unknown"]);

		bool result = long.TryParse(_userManager.GetUserId(User), out long userId);

		if (!result || userId == 0) {
			return RedirectToAction("Index", "Home");
		}

		var order = _localContext.Orders.Add(new() {
			CoffeeUserId = userId,
		}).Entity;

		await _localContext.SaveChangesAsync();;
		return View(new OrderViewModel() {
			CoffeeUserId = userId,
			OrderId = order.Id
		});
	}

	// POST: Orders/Create
	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> Create([Bind("CoffeeUser,Address,Items")] OrderViewModel viewModel) {
		// ===
		// 1. Validate ViewModel and local user instance
		// 2. Create a new local Order
		// 3. Create new local OrderItems
		// ===
		// 1. Get or create global user backup
		// 2. Add new global Order backup
		// 3. Add new global OrderItm backup

		if (!ModelState.IsValid) {
			var errors = ModelState.Values.SelectMany(v => v.Errors);
			foreach (var error in errors) {
				Console.WriteLine($"Validation Error: {error.ErrorMessage}");
			}
		}

		if (viewModel.Items == null) {
			return BadRequest();
		}

		var localUser = _localContext.Users.Find(viewModel.CoffeeUserId);

		if (localUser == null) {
			return BadRequest();
		}

		var localOrder = _localContext.Orders.Find(viewModel.OrderId);

		if (localOrder == null) {
			return BadRequest();
		}

		// Run a foreach as the OrderItem Id has to be generated by the database first
		foreach (var newItem in viewModel.Items) {
			_localContext.OrderItems.Add(new() {
				OrderId = localOrder.Id,
				CoffeeId = newItem.Id,
				Quantity = newItem.Quantity,
				UnitPrice = newItem.UnitPrice
			});
		}
		await _localContext.SaveChangesAsync();

		// TO IMPLEMENT
		//if (_globalContext.CanConnect()) {
		//	CreateGlobal();
		//}
		return RedirectToAction(nameof(Create));
	}

	// TO IMPLEMENT
	//private async Task<IActionResult> CreateGlobal() {
	//	var globalUser = _globalContext.Users.Find(localUser.GlobalId);

	//	if (globalUser == null) {
	//		// Assuming the local user is correctly validated, we back them up in the global context.
	//		globalUser = new CoffeeUser {
	//			UserName = localUser.UserName,
	//			Email = localUser.Email,
	//			FirstName = localUser.FirstName,
	//			LastName = localUser.LastName,
	//			EmailConfirmed = localUser.EmailConfirmed,
	//			PhoneNumber = localUser.PhoneNumber,
	//			CreatedAt = localUser.CreatedAt
	//		};
	//		globalUser = _globalContext.Users.Add(globalUser).Entity;
	//		await _globalContext.SaveChangesAsync();

	//		localUser.GlobalId = globalUser.Id;
	//		await _localContext.SaveChangesAsync();
	//	}

	//	var globalOrder = _globalContext.Orders.Add(new() {
	//		CoffeeUserId = globalUser.Id
	//	}).Entity;
	//	await _globalContext.SaveChangesAsync();

	//	// Run a foreach as the Order Id has to be generated by the database first
	//	foreach (var newItem in _localContext.OrderItems.Where(oi => oi.OrderId == localOrder.Id).ToArray()) {
	//		var globalCoffeeId = _globalContext.Coffees.Find(newItem.Coffee?.GlobalId)?.Id;

	//		if (globalCoffeeId == null) {
	//			continue;
	//		}

	//		_globalContext.OrderItems.Add(new() {
	//			OrderId = globalOrder.Id,
	//			CoffeeId = (long) globalCoffeeId,
	//			Quantity = newItem.Quantity,
	//			UnitPrice = newItem.UnitPrice
	//		});
	//	}
	//	await _localContext.SaveChangesAsync();
	//}

	// GET: Orders/Edit/5
	public async Task<IActionResult> Edit(long? id) {
		if (id == null)
			return NotFound();

		var order = await _localContext.Orders.FindAsync(id);
		if (order == null)
			return NotFound();

		ViewData["CoffeeUserId"] = new SelectList(_localContext.Users, "Id", "FirstName", order.CoffeeUserId);
		ViewData["StatusTypes"] = _utilities.GetEnumSelectList<StatusType>(ignored: ["Unknown"]);
		return View(order);
	}

	// POST: Orders/Edit/5
	[HttpPost]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> Edit(long id, [Bind("Id,CoffeeUserId,Status,CreatedAt,DeletedAt")] Order order) {
		if (id != order.Id)
			return NotFound();

		if (ModelState.IsValid) {
			try {
				_localContext.Update(order);
				await _localContext.SaveChangesAsync();
			} catch (DbUpdateConcurrencyException) {
				if (!OrderExists(order.Id))
					return NotFound();
				else
					throw;
			}
			return RedirectToAction(nameof(Index));
		}
		ViewData["CoffeeUserId"] = new SelectList(_localContext.Users, "Id", "FirstName", order.CoffeeUserId);
		return View(order);
	}

	// GET: Orders/Delete/5
	public async Task<IActionResult> Delete(long? id) {
		if (id == null) {
			return NotFound();
		}

		var order = await _localContext.Orders
			 .Include(o => o.CoffeeUser)
			 .FirstOrDefaultAsync(m => m.Id == id);
		if (order == null) {
			return NotFound();
		}

		return View(order);
	}

	// POST: Orders/Delete/5
	[HttpPost, ActionName("Delete")]
	[ValidateAntiForgeryToken]
	public async Task<IActionResult> DeleteConfirmed(long id) {
		var order = await _localContext.Orders.FindAsync(id);
		if (order != null) {
			_localContext.Orders.Remove(order);
		}

		await _localContext.SaveChangesAsync();
		return RedirectToAction(nameof(Index));
	}

	private bool OrderExists(long id) {
		return _localContext.Orders.Any(e => e.Id == id);
	}
}
